import Navigation from '@/components/navigation';
import styles from './layout.module.css';
import './global.css';

export const metadata = {
  title: 'Cristhian Benitez',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
